# Cogitoweb: by default there are no pages outside of Admin, therefore it is not necessary to configure the routes for this area
#sonata_user_security:
#    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_admin_security:
    resource: "@SonataUserBundle/Resources/config/routing/admin_security.xml"
    prefix:   /admin

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix:   /admin/profile

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix:   /admin/profile

sonata_user_admin_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/admin_resetting.xml"
    prefix:   /admin/resetting