# Cogitoweb: configuration based on https://sonata-project.org/bundles/user/master/doc/reference/installation.html tutorial
security:
    providers:
        fos_userbundle:
            id: fos_user.user_manager

#    encoders:
#        FOS\UserBundle\Model\UserInterface: sha512

    # Cogitoweb: disable security ACL
#    acl:
#        connection: default

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER,  ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT  # if you are using acl then this line must be commented